# Generated by Django 5.2.1 on 2025-06-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_wholesale',
            field=models.BooleanField(default=False),
        ),
    ]
