# Generated by Django 5.2.1 on 2025-06-03 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ages',
            field=models.CharField(choices=[('0-5m', '0-5 months'), ('5-8m', '5-8 months'), ('8-12m', '8-12 months'), ('1-2y', '1-2 years'), ('2-5y', '2-5 years'), ('5-8y', '5-8 years'), ('8-12y', '8-12 years'), ('12-14y', '12-14 years')], default='1-2 years', max_length=10, verbose_name='Age Group'),
            preserve_default=False,
        ),
       
    ] 
    migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default='lego', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand'),
            preserve_default=False,
        ),
