# Generated by Django 5.2.1 on 2025-06-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_new_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_wholesale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='min_wholesale_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
