# Generated by Django 5.2.1 on 2025-06-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_wholesale_product_min_wholesale_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_wholesale_quantity',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
