# Generated by Django 5.2.1 on 2025-06-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_threshold',
            field=models.PositiveIntegerField(default=10, verbose_name='Low Stock Threshold'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_stock',
            field=models.PositiveIntegerField(default=100, verbose_name='Total Stock'),
        ),
    ]
